project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Nuria Diaz" 
    right: 
      - icon: github
        href: https://github.com/
  title: "Nuria Diaz's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about 
      - href: portfolio.qmd
        text: Portfolio
      - walkthrough.qmd
      - NuriaDiaz_resume.docx
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



