---
editor: 
  markdown: 
    wrap: 72
---

I wrote this article while taking Intro to Newswritting in 2021 to
showcase the problem of domestic violence on the island and how the
pandemic exacerbated the problem.

Shelters Struggle to Stay Afloat During the COVID-19 Pandemic

By Nuria Diaz Munoz

Shelters for victims of abuse are struggling to adjust to the new health
measures due to the lack of adequate resources from the government
against the COVID-19 pandemic. Domestic violence cases rise to 83%
during the COVID-19 pandemic according to a study published on February
of this year by the Coordinadora Paz para la Mujer, Inc in Puerto Rico.

Gov. Pedro Pierluisi declared a state of emergency on Jan. 24, ordering
new government programs to educate and prevent domestic violence in
response to the number of domestic violence cases increasing by 83%
during the pandemic. Officials in charge of various shelters on the
island agreed the order is a \"step in the right direction\" but said
lack of government funding to implement the programs remains the biggest
challenge. The government has yet to implement executive order, and
shelter officials say they feel \"abandoned.\"

The women\'s law division within the Puerto Rican government has not
responded to media inquiries about the rise in domestic violence during
the pandemic. That silence has prompted the Coordinadora Paz para la
Mujer Inc, a coalition against domestic violence and sexual assault, to
investigate the government\'s inaction and the problems shelters are
facing.

Nereida Valentin, communications director of the Coordinadora Paz para
la Mujer Inc, said the government\'s women\'s law division had been
facing uncertainty since the director resigned in December 2020
abruptly. The organization has been operating throughout the pandemic
without any leadership since the end of last year. Valentin said the
division didn\'t provide shelters with enough money or other resources
and lacked a \"concrete\" plan of action for addressing domestic
violence during the pandemic.

\"Many were left uncertain on how to approach the pandemic as they were
left with an empty space at the head of the table,\" Valentin said. \"As
the situation worsened many of the current resources the division held
were stretched thin due to lack of coordination from the different
governmental departments.\"

Valentin said the government did not view shelters as essential services
during the pandemic, prioritizing health services inhospitals.  She said
vaccines and tests are arriving at a minimal quantity due to them being
processed from the mainland, which has led the government to focus on
vaccinating the population at the highest risk.

\"In the end, the division did their best with the conditions they faced
at the time which were not optimal,\" Valentin said. \"Currently we are
working with the division to form a better plan of action to alleviate
the needs of the shelters, but as it is still in process, I cannot share
the details as of today.\"

Gloria Vázquez, shelter executive director of Casa de la Bondad in
Humacao, said they struggled to communicate with many victims that took
part in the program prior to the pandemic. Shelter employees had to
create escape plans from the victim\'s homes to the shelter facilities
during the first months of the pandemic. 

\"We have focused on communicating with the victims via text messages
and calls to connect them with the professionals they needed,\" Vázquez
said. \"Sadly, we had some cases where we lost contact with many of the
victims as they were locked in with their abusers.\"

Vázquez said her shelter was able to shift all its programs onto virtual
platforms to continue providing many services to participants. She said
the shelter focused its efforts on guaranteeing many victims receive
legal services to protect them from their abusers.

\"The different regions where we bring services, which are Humacao and
Fajardo, have focused on helping the victims arrive at the facilities
and receive immediate attention to request protection orders,\" Vázquez
said. 

Vázquez said that in the past weeks after the governor issued the state
of emergency, the shelter received more women into their facilities.
They have noticed an increase in the number of women over 50 years old
in their ambulatory services program but aren\'t sure why.

\"Casa de la Bondad has continued to provide all our services even with
the current pandemic crisis,\" said Vázquez. \"We have focused our
efforts on guaranteeing the safety of all the women in our facilities.\"

Vázquez said the government has offered shelters financial aid during
the crisis, but it has yet to materialize. Like the Hogar Nueva Mujer
shelter, she said they have not received any safety gear or COVID-19
tests from the government. They are currently waiting for any update on
when employees will be able to be vaccinated.

\"It really worries us as shelter services are essential services, and
it\'s important to take care of our personnel who have been supporting
the victims and their children,\" Vazquez said. \"We are left to wait.\"
